CREATE TABLE Sheet1(QUESTIONS VARCHAR(10),RESPONSES VARCHAR(10),Column_3 VARCHAR(10));
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('','Para conectar rápido, http://sql.ldtsynergy.com','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de los Departamentos que no están en "Europe"','SELECT DEPARTMENT_NAME, CITY, COUNTRY_NAME
FROM DEPARTMENTS D JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID) JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
WHERE REGION_ID NOT IN (SELECT REGION_ID FROM COUNTRIES WHERE REGION_ID = '1')','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de los distintos cargos laborales que hay en "United Kingdom"','SELECT distinct JOB_TITLE
FROM DEPARTMENTS
JOIN LOCATIONS ON ( LOCATIONS.LOCATION_ID= DEPARTMENTS.LOCATION_ID) 
JOIN COUNTRIES ON ( COUNTRIES.COUNTRY_ID= LOCATIONS.COUNTRY_ID) 
JOIN EMPLOYEES ON (EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID) 
JOIN JOBS ON (EMPLOYEES.JOB_ID=JOBS.JOB_ID) 
WHERE COUNTRY_NAME LIKE 'United Kingdom'','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Hay una tal Julia que gana mas de 3000 en Envios (Shipping) pero no es la encargada de almacén (Stock clerk)','SELECT E.*
FROM EMPLOYEES E JOIN JOBS J ON (E.JOB_ID= J.JOB_ID) 
WHERE FIRST_NAME LIKE 'JULIA' AND JOB_TITLE LIKE 'Shipping Clerk'','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de TODOS los departamentos y que cualificaciones (jobs_title) puedo encontrar en cada uno.','SELECT DISTINCT DEPARTMENT_NAME, JOB_TITLE
FROM EMPLOYEES E
JOIN JOBS J ON (E.JOB_ID=J.JOB_ID) 
RIGHT JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de los Jefes de Departamentos y en qué ciudad están','SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D ON (E.EMPLOYEE_ID=D.MANAGER_ID) JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de TODOS los empleados indicando cargo y departamento','SELECT FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN JOBS J ON (E.JOB_ID = J.JOB_ID)','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('QUESTIONS','RESPONSES','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('','Para conectar rápido, http://sql.ldtsynergy.com','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de los Departamentos que no están en "Europe"','SELECT DEPARTMENT_NAME, CITY, COUNTRY_NAME
FROM DEPARTMENTS D JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID) JOIN COUNTRIES C ON (L.COUNTRY_ID = C.COUNTRY_ID)
WHERE REGION_ID NOT IN (SELECT REGION_ID FROM COUNTRIES WHERE REGION_ID = '1')','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de los distintos cargos laborales que hay en "United Kingdom"','SELECT distinct JOB_TITLE
FROM DEPARTMENTS
JOIN LOCATIONS ON ( LOCATIONS.LOCATION_ID= DEPARTMENTS.LOCATION_ID) 
JOIN COUNTRIES ON ( COUNTRIES.COUNTRY_ID= LOCATIONS.COUNTRY_ID) 
JOIN EMPLOYEES ON (EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID) 
JOIN JOBS ON (EMPLOYEES.JOB_ID=JOBS.JOB_ID) 
WHERE COUNTRY_NAME LIKE 'United Kingdom'','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Hay una tal Julia que gana mas de 3000 en Envios (Shipping) pero no es la encargada de almacén (Stock clerk)','SELECT E.*
FROM EMPLOYEES E JOIN JOBS J ON (E.JOB_ID= J.JOB_ID) 
WHERE FIRST_NAME LIKE 'JULIA' AND JOB_TITLE LIKE 'Shipping Clerk'','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de TODOS los departamentos y que cualificaciones (jobs_title) puedo encontrar en cada uno.','SELECT DISTINCT DEPARTMENT_NAME, JOB_TITLE
FROM EMPLOYEES E
JOIN JOBS J ON (E.JOB_ID=J.JOB_ID) 
RIGHT JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de los Jefes de Departamentos y en qué ciudad están','SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D ON (E.EMPLOYEE_ID=D.MANAGER_ID) JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)','');
INSERT INTO Sheet1 (QUESTIONS,RESPONSES,Column_3) VALUES ('Listado de TODOS los empleados indicando cargo y departamento','SELECT FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN JOBS J ON (E.JOB_ID = J.JOB_ID)','');
